// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package postusers

import (
	http "net/http"

	logger "github.com/MSex/lab-go-http/app/logger"
	mock "github.com/stretchr/testify/mock"
)

// RequestHelperMock is an autogenerated mock type for the ResponseHelper type
type ResponseHelperMock struct {
	mock.Mock
}

// WriteBody provides a mock function with given fields: body, httpWriter, _a2
func (_m *ResponseHelperMock) WriteBody(body ResponseBody, httpWriter http.ResponseWriter, _a2 logger.Logger) {
	_m.Called(body, httpWriter, _a2)
}

// WriteError provides a mock function with given fields: code, err, httpWriter, _a3
func (_m *ResponseHelperMock) WriteError(code int, err error, httpWriter http.ResponseWriter, _a3 logger.Logger) {
	_m.Called(code, err, httpWriter, _a3)
}
